language: cpp
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install: sudo apt -y install qt5-default
compiler: g++
script:
    - export CC=gcc-7
    - export CXX=g++-7
    - mkdir build
    - cd build
    - cmake ../src
    - make
